### ISSUE TITLE
Add SASL support to proxy side

### ISSUE THREAD

**Issue by akme** [Netflix/rend#106]
Hi,
Any plans to add SASL support to proxy side? It'll be nice to move auth from memcached nodes to proxy server, because proxy servers usually have better CPU and gives more unified way to auth requests.

**Comment by ScottMansfield** [comment]
It's something that I hadn't considered yet, mostly because we didn't need it. We were also looking at adding some SSL support with custom certificates, but that's somewhere middle of the list.

I will take a look at SASL, since I know very little about it, and see how it can be done.

I also encourage you to take a look at implementing it yourself, and I will help review if you choose to do so.

**Comment by ScottMansfield** [comment]
@akme currently we're not planning on adding in the SASL support as we have another internal system with which we will be integrating in the future for security between client and server. If you want to take a stab at it, that's fine, but this is not in our plans. I'm closing this as we're not going to implement this.
